### ISSUE TITLE
Crash on server startup for 1.9

### ISSUE THREAD

**Issue by kwpugh** [61352151511/Random-Utilities#1]
Crash report:  http://pastebin.com/raw/FazQUT6e

Forge:  forge-1.9-12.16.0.1803-1.9-universal.jar
Mod:  Random Utilities-1.9-3.0.0.jar

**Comment by 61352151511** [comment]
Should be fixed in 3.0.1, please test.

**Comment by kwpugh** [comment]
Sorry, no joy.

Crash report:  http://pastebin.com/raw/WA4jUjju

**Comment by 61352151511** [comment]
Oh, I understand the issue. Should have it fixed soon

**Comment by 61352151511** [comment]
Try this version before I upload it to curseforge. This hopefully fixes it. https://dl.dropboxusercontent.com/u/105870951/Random%20Utilities-1.9-3.0.2.jar

**Comment by kwpugh** [comment]
Server starts up fine, looks good.   Thank you.
