### ISSUE TITLE
Magic Chest not accepting input from a hopper

### ISSUE THREAD

**Issue by DreamingLamb** [61352151511/Random-Utilities#5]
I think the titles says most of it, but basically I cannot input items into a Magic Chest using a Hopper in 1.9, v3.0.3.

I have tried adding food to an Automatic Lunchbox and also inputting items into an empty chest from all sides and the top.

**Comment by 61352151511** [comment]
Try 1.9.4, Although the code should also be present for 3.0.3 I have tested it in the latest version of the mod. Placing down a magic chest, putting in a lunchbox, putting in a magic card, and then connecting a hopper and filling the hopper with food, works for me.

**Comment by DreamingLamb** [comment]
I'll see if I can test 1.9.4 in a couple of days but I can't update our server as there are a few mods that haven't been updated yet.

That sounds like exactly what I've done, should it still work with an automatic Lunchbox/Heart Canister?

**Comment by 61352151511** [comment]
Yes, it does still work with automatic lunch/HC. Just tested it.

**Comment by DreamingLamb** [comment]
Ok, weird.  I'll test a few things and get back to you.  I wont have my laptop until Wednesday though.

Just as a fyi, I've tried placing baked potatoes, carrots and bread in the hopper and each failed to transfer, also, the lunchbox is not full (you never know).

**Comment by 61352151511** [comment]
Send me a few pictures when you can. If the lunchbox is close to being full, it will not take the food. IE if an apple fills 2 food bars, and the lunchbox is at 99/100, it will not accept it.

**Comment by DreamingLamb** [comment]
Ok, so I created two new Curse profiles with just Random Utilities (one for 1.9 and one for 1.9.4) and both worked.  My apologies, maybe there's another mod that's doing something with food, I have no idea what happened, but thank you for getting back to me and your time!
