### ISSUE TITLE
[1.9.4] Server crash when using /home

### ISSUE THREAD

**Issue by kwpugh** [61352151511/Random-Utilities#6]
randomly the server will crash when players use a previously set /home.

Forge: 1957
Mod: Random Utilities-1.9.4-3.1.1.jar

Crash report:  http://pastebin.com/raw/JZwMYE1T

**Comment by 61352151511** [comment]
I don't see anything about random utilities in there. It could very well be me but it could be a coremod that you have

**Comment by kwpugh** [comment]
I understand.   I have been struggle to figure out what is the root of this.   The only common denominator is that the crashes happen when a player does /home.   I was hoping your eyes on this might spark something.

**Comment by 61352151511** [comment]
It's a possibility that when someone does /home if someone does it as well at the same time it could happen but if it's everytime someone does it then I don't think so

**Comment by kwpugh** [comment]
it doesn't happen everytime.   it has happened with only one person on the server.

**Comment by 61352151511** [comment]
Hmmm that's odd, I'll try to look into it but by the looks of it, it could be a coremod that does something with EntityTracker.

**Comment by 61352151511** [comment]
Please comment if you still have issues in 1.12
