### ISSUE TITLE
Client Crash When I accidentally kill myself at the altar(repeated)

### ISSUE THREAD

**Issue by pactuslupus** [61352151511/Random-Utilities#7]
[crash-2016-07-19_13.06.03-client.txt](https://github.com/61352151511/Random-Utilities/files/372585/crash-2016-07-19_13.06.03-client.txt)
[crash-2016-07-18_21.28.03-client.txt](https://github.com/61352151511/Random-Utilities/files/372586/crash-2016-07-18_21.28.03-client.txt)

Not sure what other information you need. Let me know if you need more.

**Comment by 61352151511** [comment]
Please comment if you still have issues in 1.12
