### ISSUE TITLE
Display Table cause Client Crash

### ISSUE THREAD

**Issue by MSandro** [61352151511/Random-Utilities#8]
Minecraft: 1.12
Mod version: 5.0.1

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  CXLibraryCore (cxlibrary-1.12-1.5.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12-1.9.jar)
  Default Options (DefaultOptions_1.12-9.2.1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.3-1.12-anarchy.jar)
  OpenEyePlugin (OpenEye-1.12-0.8.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  AstralCore (astralsorcery-1.12-1.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  CoreModLoader (applied-llamagistics-1.12-rv5-alpha-5.jar)
  HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 7/19/17 2:36 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at com.sixonethree.randomutilities.client.render.tileentity.DisplayTableRenderer.render(DisplayTableRenderer.java:57)
	at com.sixonethree.randomutilities.client.render.tileentity.DisplayTableRenderer.func_192841_a(DisplayTableRenderer.java:14)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:704)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.sixonethree.randomutilities.client.render.tileentity.DisplayTableRenderer.render(DisplayTableRenderer.java:57)
	at com.sixonethree.randomutilities.client.render.tileentity.DisplayTableRenderer.func_192841_a(DisplayTableRenderer.java:14)

-- Block Entity Details --
Details:
	Name: minecraft:tileentitydisplaytable // com.sixonethree.randomutilities.common.block.tile.TileEntityDisplayTable
	Block type: ID #1718 (tile.randomutilities:display_table // com.sixonethree.randomutilities.common.block.BlockDisplayTable)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (577,69,188), Chunk: (at 1,4,12 in 36,11; contains blocks 576,0,176 to 591,255,191), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #1718 (tile.randomutilities:display_table // com.sixonethree.randomutilities.common.block.BlockDisplayTable)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:704)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1336)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MSandro'/784, l='MpServer', x=577.24, y=69.00, z=186.83]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (240,64,60), Chunk: (at 0,4,12 in 15,3; contains blocks 240,0,48 to 255,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1367043 game time, 437860 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 31 total; [EntityBat['Bat'/56832, l='MpServer', x=577.25, y=31.65, z=142.41], EntityItem['item.item.white_egg'/55817, l='MpServer', x=604.21, y=66.00, z=229.56], EntityPig['Pig'/793, l='MpServer', x=532.55, y=63.00, z=134.76], EntityPig['Pig'/794, l='MpServer', x=542.66, y=66.00, z=132.55], EntitySheep['Sheep'/795, l='MpServer', x=541.81, y=69.00, z=123.36], EntityMinecartChest['Minecart with Chest'/800, l='MpServer', x=548.50, y=34.06, z=133.50], EntitySheep['Sheep'/806, l='MpServer', x=550.56, y=68.00, z=118.79], EntityPig['Pig'/807, l='MpServer', x=577.35, y=74.00, z=138.79], EntityMinecartChest['Minecart with Chest'/808, l='MpServer', x=567.50, y=34.06, z=154.50], EntityWhiteChicken['White Chicken'/40242, l='MpServer', x=604.31, y=66.00, z=230.06], EntityItem['item.item.dyePowder.white'/40243, l='MpServer', x=604.13, y=66.00, z=230.33], EntitySheep['Sheep'/40247, l='MpServer', x=653.55, y=70.00, z=231.10], EntitySheep['Sheep'/40248, l='MpServer', x=529.49, y=69.00, z=234.74], EntityItem['item.item.dyePowder.white'/52538, l='MpServer', x=615.69, y=64.00, z=211.31], EntitySheep['Sheep'/826, l='MpServer', x=648.50, y=67.00, z=222.19], EntitySheep['Sheep'/40251, l='MpServer', x=513.29, y=67.00, z=243.48], EntitySheep['Sheep'/828, l='MpServer', x=622.82, y=66.00, z=214.15], EntityWhiteChicken['White Chicken'/843, l='MpServer', x=616.12, y=64.00, z=211.70], EntityMorph['Morph'/12121, l='MpServer', x=606.91, y=69.00, z=177.90], EntityPlayerSP['MSandro'/784, l='MpServer', x=574.77, y=69.00, z=161.70], EntityZombie['Zombie'/55937, l='MpServer', x=583.50, y=29.00, z=115.50], EntitySheep['Sheep'/41091, l='MpServer', x=620.46, y=63.00, z=259.80], EntitySheep['Sheep'/40330, l='MpServer', x=513.50, y=68.00, z=245.50], EntitySheep['Sheep'/40331, l='MpServer', x=512.50, y=68.00, z=246.50], EntityPlayerSP['MSandro'/784, l='MpServer', x=577.24, y=69.00, z=186.83], EntityItem['item.item.dyePowder.black'/56489, l='MpServer', x=597.34, y=46.00, z=209.88], EntityMorph['Morph'/10923, l='MpServer', x=617.80, y=65.00, z=208.70], EntityPig['Pig'/16583, l='MpServer', x=549.32, y=65.00, z=108.50], EntityItem['item.item.white_egg'/55770, l='MpServer', x=615.95, y=64.00, z=211.75], EntitySquid['Squid'/57075, l='MpServer', x=518.28, y=60.70, z=143.12], EntityBabySquid['Baby Squid'/57078, l='MpServer', x=542.53, y=59.33, z=168.39]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 846364168 bytes (807 MB) / 4049600512 bytes (3862 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.40 Powered by Forge 14.21.1.2413 151 mods loaded, 150 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2413.jar) 
	UCHIJA	forge{14.21.1.2413} [Minecraft Forge] (forge-1.12-14.21.1.2413.jar) 
	UCHIJA	appliedenergistics2-core{rv5-alpha-5} [Applied Llamagistics Core] (minecraft.jar) 
	UCHIJA	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJA	OpenEye{0.8} [OpenEye] (OpenEye-1.12-0.8.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	msutilities{1.2.1} [MS Utilities] ([1.12] MS Utilities-1.2.1.jar) 
	UCHIJA	actuallyadditions{1.12-r115} [Actually Additions] (ActuallyAdditions-1.12-r115.jar) 
	UCHIJA	aiimprovements{0.0.1.3} [AI Improvements] (AIImprovements-1.12-0.0.1b3.jar) 
	UCHIJA	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCHIJA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCHIJA	ic2{2.8.7-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.7-ex112.jar) 
	UCHIJA	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCHIJA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJA	cofhcore{4.3.2} [CoFH Core] (CoFHCore-1.12-4.3.2.7-universal.jar) 
	UCHIJA	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHIJA	thermalfoundation{2.3.2} [Thermal Foundation] (ThermalFoundation-1.12-2.3.2.8-universal.jar) 
	UCHIJA	thermalexpansion{5.3.2} [Thermal Expansion] (ThermalExpansion-1.12-5.3.2.10-universal.jar) 
	UCHIJA	appliedenergistics2{rv5-alpha-5} [Applied Llamagistics] (applied-llamagistics-1.12-rv5-alpha-5.jar) 
	UCHIJA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJA	mantle{1.12-1.3.0.8} [Mantle] (Mantle-1.12-1.3.0.8.jar) 
	UCHIJA	thedragonlib{1.12-4.1.0} [TheDragonLib] (thedragonlib-1.12-4.1.0.jar) 
	UCHIJA	armorplus{1.12-11.3.4.11-alpha} [ArmorPlus] (armorplus-1.12-11.3.4.11-alpha.jar) 
	UCHIJA	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCHIJA	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCHIJA	astralsorcery{1.6} [Astral Sorcery] (astralsorcery-1.12-1.6.jar) 
	UCHIJA	psi{r1.1-52} [Psi] (Psi-r1.1-52.jar) 
	UCHIJA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.12-1.5.4.jar) 
	UCHIJA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCHIJA	bedrockbgone{4.1.6} [Bedrock-B-Gone] (BedrockBGone-1.12-4.1-b6-dev.jar) 
	UCHIJA	bettertitlescreen{1.4} [Better Title Screen] (BetterTitleScreen-1.12-1.4.jar) 
	UCHIJA	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCHIJA	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCHIJA	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCHIJA	brandonscore{2.3.0} [Brandon's Core] (BrandonsCore-1.12-2.3.0.119-universal.jar) 
	UCHIJA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJA	chancecubes{1.12-3.0.1.199} [Chance Cubes] (ChanceCubes-1.12-3.0.1.199.jar) 
	UCHIJA	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UCHIJA	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCHIJA	cnoapm{1.0 by Dot_Silver} [Craftable Notch Apple Mod - MCVersion 1.11.2] (cnoapm-mcv1.12-nojson.jar) 
	UCHIJA	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCHIJA	colossalchests{1.6.4} [Colossal Chests] (ColossalChests-1.12-1.6.4.jar) 
	UCHIJA	crafttweaker{3.0.26} [CraftTweaker2] (CraftTweaker2-1.12-4.0.0.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.0.jar) 
	UCHIJA	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHIJA	custommainmenu{2.0.6} [Custom Main Menu] (CustomMainMenu-MC1.12-2.0.6.jar) 
	UCHIJA	cxlibrary{1.5.1} [CXLibrary] (cxlibrary-1.12-1.5.1.jar) 
	UCHIJA	cyclicmagic{1.6.1} [Cyclic] (Cyclic-1.12-1.6.1.jar) 
	UCHIJA	darkutils{1.6.162} [Dark Utilities] (DarkUtils-1.12-1.6.162.jar) 
	UCHIJA	defaultoptions{9.2.1} [Default Options] (DefaultOptions_1.12-9.2.1.jar) 
	UCHIJA	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCHIJA	draconicevolution{2.3.0} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.0.254-universal.jar) 
	UCHIJA	dungeondq{10.00} [DungeonDQ] (DungeonDQ_Ver10.00_[MC1.12](forge-1.12-14.21.1.2387).jar) 
	UCHIJA	durabilityshow{5.0.0} [Durability Show] (Durability Show-1.12-5.0.0.jar) 
	UCHIJA	forestry{5.4.3.134} [Forestry] (forestry_1.12-5.4.3.134.jar) 
	UCHIJA	eleccore{1.8.428} [ElecCore] (ElecCore-1.12-1.8.428.jar) 
	UCHIJA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJA	embers{0.221} [Embers] (embers-0.221.jar) 
	UCHIJA	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCHIJA	theoneprobe{1.4.13} [The One Probe] (theoneprobe-1.12-1.4.13.jar) 
	UCHIJA	endercrop{1.12-1.3.4} [Ender Crop] (endercrop-1.12-1.3.4.jar) 
	UCHIJA	shetiphiancore{3.5.0.2} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.2.jar) 
	UCHIJA	endertanks{1.6.0.2} [EnderTanks] (endertanks-1.12.0-1.6.0.2.jar) 
	UCHIJA	enderutilities{0.7.2} [Ender Utilities] (enderutilities-1.12.0-0.7.2.jar) 
	UCHIJA	energyconverters{1.0.0.1} [Energy Converters] (energyconverters_1.12-1.0.0.1.jar) 
	UCHIJA	equal_dragons{1.0} [EqualDragons] (EqualDragons-1.0.jar) 
	UCHIJA	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCHIJA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJA	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.3-1.12-anarchy.jar) 
	UCHIJA	foamflower{1.12-0.0.1.0} [Foamflower] (foamflower-1.12-0.0.1.0.jar) 
	UCHIJA	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCHIJA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCHIJA	glaretorch{8.10} [GlareTorch] (GlareTorch_Ver.8.11_[MC1.12](forge-1.12-14.21.1.2387).jar) 
	UCHIJA	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHIJA	hammercore{1.9.3.6} [Hammer Core] (HammerCore-1.12-1.9.3.6.jar) 
	UCHIJA	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.12-1.9.jar) 
	UCHIJA	immersiveengineering{0.12-66} [Immersive Engineering] (ImmersiveEngineering-0.12-66.jar) 
	UCHIJA	immersivepetroleum{1.0.10} [Immersive Petroleum] (immersivepetroleum-1.12-1.0.10.jar) 
	UCHIJA	teslacorelib{1.12-1.0.4} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.4.jar) 
	UCHIJA	industrialforegoing{1.11.2-1.0-BETA} [Industrial Foregoing] (industrialforegoing-1.12-1.0-BETA-17.jar) 
	UCHIJA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJA	journeymap{1.12-5.4.8} [JourneyMap] (journeymap-1.12-5.4.8.jar) 
	UCHIJA	jeresources{0.8.1.14} [Just Enough Resources] (JustEnoughResources-1.12-0.8.1.14.jar) 
	UCHIJA	manawell{0.0.2} [Mana Wells] (manawell-1.12--0.0.2.jar) 
	UCHIJA	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.12.jar) 
	UCHIJA	minecolonies{1.12-0.8.3167} [MineColonies] (minecolonies-universal-1.12-0.8.3167.jar) 
	UCHIJA	minecoprocessors{1.12-1.2} [Minecoprocessors] (minecoprocessors-1.12-1.2.jar) 
	UCHIJA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJA	morefurnaces{1.10.1} [More Furnaces] (MoreFurnaces-1.12-1.10.1.jar) 
	UCHIJA	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCHIJA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.12.jar) 
	UCHIJA	mputils{1.4.1} [MPUtils] (MPUtils-1.12-1.4.1.jar) 
	UCHIJA	mpbasic{1.3.0} [ModPack Basic Tools] (mpbasic-1.12-1.3.0.jar) 
	UCHIJA	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1a.jar) 
	UCHIJA	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCHIJA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJA	obsidianplates{1.3.0} [Obsidian Plates] (ObsidianPlates-1.3.0_1.12.jar) 
	UCHIJA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UCHIJA	orecontrol{0.4.0} [Ore Control] (orecontrol-1.12.0-0.4.0.jar) 
	UCHIJA	oreexcavation{1.4.100} [OreExcavation] (OreExcavation-1.4.100.jar) 
	UCHIJA	overloaded{0.0.26} [Overloaded] (Overloaded-1.12-0.0.26.jar) 
	UCHIJA	persistentbits{1.0.6a} [Persistent Bits] (PersistentBits-1.12-1.0.6a.jar) 
	UCHIJA	personalcars{1.3} [Personal Cars] (PersonalCars-1.3.jar) 
	UCHIJA	pillar_extension_biomesoplenty{2.2.0} [Corail Pillar - Biomes O'Plenty Extension] (pillar_extension_biomesoplenty-2.2.0-1.12.0.jar) 
	UCHIJA	pillar_extension_forestry{1.1.0} [Corail Pillar - Forestry Extension] (pillar_extension_forestry-1.1.0-1.12.0.jar) 
	UCHIJA	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHIJA	projecttable{1.1.1} [Project Table] (ProjectTable-1.1.1_1.12.jar) 
	UCHIJA	reborncore{3.2.4.86} [Reborn Core] (RebornCore-1.12-3.2.4.86-universal.jar) 
	UCHIJA	quantumstorage{4.3.5} [QuantumStorage] (QuantumStorage-1.12-4.3.5.jar) 
	UCHIJA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHIJA	randomutilities{5.0.1} [Random Utilities] (Random Utilities-1.12-5.0.1.jar) 
	UCHIJA	randomthings{4.0.3} [Random Things] (RandomThings-MC1.12-4.0.3.jar) 
	UCHIJA	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCHIJA	reauth{3.5.1} [ReAuth] (ReAuth-3.5.1.jar) 
	UCHIJA	redstonearsenal{2.3.2} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.2.6-universal.jar) 
	UCHIJA	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.8.jar) 
	UCHIJA	refinedstorage{1.5.11} [Refined Storage] (refinedstorage-1.5.11.jar) 
	UCHIJA	resourceloader{1.5.2} [Resource Loader] (ResourceLoader-MC1.12-1.5.2.jar) 
	UCHIJA	rftools{6.10} [RFTools] (rftools-1.12-6.10beta4.jar) 
	UCHIJA	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCHIJA	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJA	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCHIJA	silentgems{2.4.2} [Silent's Gems] (SilentsGems-1.12-2.4.2-206.jar) 
	UCHIJA	simplevoidworld{1.2.0.1} [SimpleVoidWorld] (Simple-Void-World-1.12-1.2.0.1-universal.jar) 
	UCHIJA	simpleharvest{1.07} [Simple Harvest] (simpleharvest-1.07.jar) 
	UCHIJA	lteleporters{1.11.2-2.1.5} [Simple Teleporters] (simpleteleporters-1.12-2.1.5.jar) 
	UCHIJA	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCHIJA	solarfluxreborn{3.25r} [Solar Flux Reborn] (SolarFluxReborn_1.12-3.25r.jar) 
	UCHIJA	soulshardstow{1.12-2.7.3-52} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.3-52.jar) 
	UCHIJA	statues{0.7.1.1} [Statues mod] (statues-0.7.1.1.jar) 
	UCHIJA	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.4.25.jar) 
	UCHIJA	thermaldynamics{2.3.2} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.2.9-universal.jar) 
	UCHIJA	thutcore{5.5.0} [Thut Core] (thutcore-5.5.0.jar) 
	UCHIJA	thuttech{6.0.2} [Thut's Tech] (thuttech-6.0.2.jar) 
	UCHIJA	muchmorechickens{1.6} [muchmorechickens] (TMC-1.12-1.5.jar) 
	UCHIJA	topaddons{1.12-0.15.0} [TOP Addons] (topaddons-1.12-0.15.0.jar) 
	UCHIJA	torchmaster{1.4.3.8} [TorchMaster] (torchmaster_1.12-1.4.3.8.jar) 
	UCHIJA	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UCHIJA	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCHIJA	wearablebackpacks{3.0.3} [Wearable Backpacks] (WearableBackpacks-1.12-3.0.3.jar) 
	UCHIJA	xnet{1.3.5} [XNet] (xnet-1.12-1.3.5.jar) 
	UCHIJA	xtones{1.12-1.0.4-7} [Xtones] (Xtones-1.12-1.0.4-7.jar) 
	UCHIJA	yabba{1.12-0.5.3} [YABBA] (YABBA-1.12-0.5.3.jar) 
	UCHIJA	corail_pillar{2.2.0} [Corail Pillar] (corail_pillar-2.2.0-1.12.0.jar) 
	UCHIJA	teslacoreregistries{1.12-1.0.4} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.4.jar) 
	UD	solarfluxreborncore{3.25r} [Solar Flux Reborn: Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.12-1.5.1.jar)
  cubex2.cxlibrary.CoreModTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
LoadingPlugin (RandomThings-MC1.12-4.0.3.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.12-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
Default Options (DefaultOptions_1.12-9.2.1.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.3-1.12-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
OpenEyePlugin (OpenEye-1.12-0.8.jar)
  openeye.asm.MultiTransformer
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  shetiphian.asm.ClassTransformer
AstralCore (astralsorcery-1.12-1.6.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreModLoader (applied-llamagistics-1.12-rv5-alpha-5.jar)
  appeng.coremod.transformer.ASMIntegration
HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 980M/PCIe/SSE2'
	AE2 Version: alpha rv5-alpha-5 for Forge 14.21.1.2387
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.4.86
		Runtime Debofucsation 1
		RenderEngine: 0
	AE2 Integration: IC2:ON, BUILDCRAFT:OFF, COFH_HAMMER:ON, RF:OFF, RFItem:OFF, Waila:OFF, JEI:ON, OpenComputers:OFF, THE_ONE_PROBE:ON
	Launched Version: forge-14.21.1.2413
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz

**Comment by 61352151511** [comment]
Fixed for 5.0.2
